typography_spectrum: 0.66319
color:
  brandColors:
    - '#ffffff'
    - '#bed63c'
    - '#8bc63f'
    - '#b9d98c'
    - '#d5e7c0'
  brandStrength: 0.9875533694867045
  lightness: 0.625
  saturation: 0.28095115232281387
  rhythmicContrast: 0.8559714325238019
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.666666
analytics:
  google: null
  facebook: null
  twitter: null
name: RigaBrain atsauksmes
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: RigaBrain
    url: 'http://www.rigabrain.com/'
    type: external
favicon: null
title: >-
  Katu dienu, tiek uzrakstīta kāda atsauksme par RigaBrain. Un tā jau kopš 2008.
  gada!
purpose: []
