analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#bed63c'
    - '#8bc63f'
    - '#b9d98c'
    - '#d5e7c0'
  brandStrength: 0.9875533694867045
  lightness: 0.625
  rhythmicContrast: 0.8559714325238019
  saturation: 0.28095115232281387
cta: {}
layout_spectrum: 0.666666
name: RigaBrain atsauksmes
opengraph: {}
purpose: []
typography_spectrum: 0.66319
