name: RigaBrain atsauksmes
favicon: null
layout_spectrum: 0.2336922399699688
typography_spectrum: 0.22416678350418806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9875533694867045
  lightness: 0.5422267727553844
  saturation: 0.28095115232281387
  rhythmicContrast: 0.8559714325238019
purpose: []
